---
name: Verify README.md is up-to-date

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:

jobs:
  verify-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true

      - name: Generate README.md and STATUS.md
        run: |
          bundle exec rake docs:readme > README.md.new
          diff -u README.md README.md.new
          bundle exec rake docs:status > STATUS.md.new
          diff -u STATUS.md STATUS.md.new
